apiVersion: v1
kind: Service
metadata:
  name: k8s-watcher-service
spec:
  type: ClusterIP  # 또는 LoadBalancer, NodePort 등
  ports:
  - port: 80  # 서비스가 노출할 포트
    targetPort: 8080  # 컨테이너의 포트 (필요시 수정)
  selector:
    app: k8s-watcher